apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tea-tekton-knative
  namespace: default
spec:
  template:
    spec:
      volumes:
      - name: secret-volume-2
        secret:
          secretName: jdbc-secret
      containers:
      - name: tea-tekton-knative
        image: image-registry.openshift-image-registry.svc:5000/default/tea-tekton:latest
        ports:
        - containerPort: 7800
        volumeMounts:
        - name: secret-volume-2
          mountPath: /var/run/secrets/jdbc
